output_dir: ~/scratch/protst_output/
checkpoint: {{ checkpoint }}

dataset:
  class: {{ dataset }} # BinaryLocalization / SubcellularLocalization
  path: ~/scratch/protein-datasets/
  atom_feature: null
  bond_feature: null
  transform:
    class: Compose
    transforms:
      - class: TruncateProtein
        max_length: 550
        random: True
      - class: ProteinView
        view: "residue"

task:
  class: PropertyPrediction
  model:
    class: PretrainESM
    path: ~/scratch/esm-model-weights/
    model: ESM-2-650M
    mask_modeling: False
    output_dim: 512
    readout: mean
    use_proj: False
  criterion: ce
  metric: ["acc", "mcc"]
  num_mlp_layer: 2
  num_class: {{ num_class }}

eval_metric: accuracy

optimizer:
  class: Adam
  lr: 2.0e-4

lr_ratio: 0.02

engine:
  gpus: [0, 1, 2, 3]
  batch_size: 3

train:
  num_epoch: 100
