output_dir: ~/scratch/protst_output/
checkpoint: {{ checkpoint }}

dataset:
  class: {{ dataset }} # SubcellularLocalization / Reaction
  path: ~/scratch/protein-datasets/
  atom_feature: null
  bond_feature: null
  transform:
    class: Compose
    transforms:
      - class: ProteinView
        view: "residue"

task:
  class: PropertyPrediction
  model:
    class: ESM
    path: ~/scratch/esm-model-weights/
    model: ESM-1b
    readout: mean
  criterion: ce
  metric: ["acc", "mcc"]
  num_mlp_layer: 2
  num_class: {{ num_class }} # Reaction: 384; SubcellularLocalization: 10

eval_metric: accuracy

optimizer:
  class: Adam
  lr: 5.0e-5

fix_encoder: True

engine:
  gpus: [0]
  batch_size: 8

train:
  num_epoch: 100
